I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 40, in script
    define a = Character(aname, image = "ichikocasualsmile.png")
  File "game/script.rpy", line 40, in script
    define a = Character(aname, image = "ichikocasualsmile.png")
  File "game/script.rpy", line 40, in <module>
    define a = Character(aname, image = "ichikocasualsmile.png")
NameError: name 'aname' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "/Users/jess/Desktop/renpy-8.0.3-sdk/renpy/bootstrap.py", line 277, in bootstrap
    renpy.main.main()
  File "/Users/jess/Desktop/renpy-8.0.3-sdk/renpy/main.py", line 558, in main
    renpy.game.context().run(node)
  File "game/script.rpy", line 40, in script
    define a = Character(aname, image = "ichikocasualsmile.png")
  File "/home/tom/ab/renpy-build/tmp/install.linux-x86_64/lib/python3.9/site-packages/future/utils/__init__.py", line 441, in raise_
  File "game/script.rpy", line 40, in script
    define a = Character(aname, image = "ichikocasualsmile.png")
  File "/Users/jess/Desktop/renpy-8.0.3-sdk/renpy/ast.py", line 2441, in execute
    self.set()
  File "/Users/jess/Desktop/renpy-8.0.3-sdk/renpy/ast.py", line 2455, in set
    value = renpy.python.py_eval_bytecode(self.code.bytecode)
  File "/Users/jess/Desktop/renpy-8.0.3-sdk/renpy/python.py", line 1085, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/script.rpy", line 40, in <module>
    define a = Character(aname, image = "ichikocasualsmile.png")
NameError: name 'aname' is not defined

macOS-10.16-x86_64-i386-64bit x86_64
Ren'Py 8.0.3.22090809
amazing_first_project 1.0
Mon Sep 26 15:20:39 2022
